import type { BasicColumn, FormSchema } from '/@/components/Table';
// import { productCategorySelectOptions } from '../productCategory/productCategory.data';

export type ProductStatus = 'available' | 'disabled';
export type ProductSalesType = 'single' | 'combo' | 'service';

export interface ProductItem {
  id: string;
  productCode: string;
  productName: string;
  categoryCode: string;
  categoryName: string;
  barcode: string;
  unit: string;
  specification: string;
  price: number;
  memberPrice: number;
  costPrice: number;
  inventory: number;
  safetyStock: number;
  tags: string[];
  supplier: string;
  manager: string;
  status: ProductStatus;
  salesType: ProductSalesType;
  createdAt: string;
  updatedAt: string;
  remark?: string;
}

export const productStatusOptions = [
  { label: '在售', value: 'available' },
  { label: '停售', value: 'disabled' },
];

export const salesTypeOptions = [
  { label: '单品', value: 'single' },
  { label: '组合套餐', value: 'combo' },
  { label: '服务项目', value: 'service' },
];

export const productColumns: BasicColumn[] = [
  {
    title: '商品编码',
    dataIndex: 'productCode',
    width: 140,
    align: 'left',
  },
  {
    title: '商品名称',
    dataIndex: 'productName',
    width: 200,
    align: 'left',
  },
  {
    title: '所属分类',
    dataIndex: 'categoryName',
    width: 140,
    align: 'left',
  },
  {
    title: '条形码',
    dataIndex: 'barcode',
    width: 160,
    align: 'left',
  },
  {
    title: '销售类型',
    dataIndex: 'salesType',
    width: 120,
    slots: { customRender: 'salesType' },
  },
  {
    title: '销售单价(元)',
    dataIndex: 'price',
    width: 130,
    align: 'right',
    format: (record) => Number(record.price ?? 0).toFixed(2),
  },
  {
    title: '会员价(元)',
    dataIndex: 'memberPrice',
    width: 120,
    align: 'right',
    format: (record) => Number(record.memberPrice ?? 0).toFixed(2),
  },
  {
    title: '库存数量',
    dataIndex: 'inventory',
    width: 110,
  },
  {
    title: '安全库存',
    dataIndex: 'safetyStock',
    width: 110,
  },
  {
    title: '负责人',
    dataIndex: 'manager',
    width: 120,
  },
  {
    title: '供应商',
    dataIndex: 'supplier',
    width: 150,
    align: 'left',
  },
  {
    title: '状态',
    dataIndex: 'status',
    width: 100,
    slots: { customRender: 'status' },
  },
  {
    title: '更新时间',
    dataIndex: 'updatedAt',
    width: 180,
  },
];

export const productSearchFormSchema: FormSchema[] = [
  {
    label: '商品名称',
    field: 'productName',
    component: 'Input',
    colProps: { span: 6 },
    componentProps: {
      placeholder: '支持编码、名称模糊查询',
    },
  },
  {
    label: '所属分类',
    field: 'categoryCode',
    component: 'Select',
    colProps: { span: 6 },
    componentProps: {
      allowClear: true,
      options: null,
    },
  },
  {
    label: '销售类型',
    field: 'salesType',
    component: 'Select',
    colProps: { span: 6 },
    componentProps: {
      allowClear: true,
      options: salesTypeOptions,
    },
  },
  {
    label: '状态',
    field: 'status',
    component: 'Select',
    colProps: { span: 6 },
    componentProps: {
      allowClear: true,
      options: productStatusOptions,
    },
  },
  {
    label: '供应商',
    field: 'supplier',
    component: 'Input',
    colProps: { span: 6 },
  },
];

export const mockProductList: ProductItem[] = [
  {
    id: 'P-1001',
    productCode: 'P-DR-50001',
    productName: '冷萃咖啡原液 500ml',
    categoryCode: 'BEV',
    categoryName: '饮料冲调',
    barcode: '6935265310001',
    unit: '瓶',
    specification: '500ml',
    price: 38,
    memberPrice: 32.5,
    costPrice: 18,
    inventory: 120,
    safetyStock: 60,
    tags: ['咖啡', '新品'],
    supplier: '杭州潮选饮品有限公司',
    manager: '李华',
    status: 'available',
    salesType: 'single',
    createdAt: '2025-08-01 09:12:00',
    updatedAt: '2025-09-26 15:32:00',
    remark: '冷链运输，需保持2-6℃存储',
  },
  {
    id: 'P-1002',
    productCode: 'P-SN-20018',
    productName: '黑松露夏威夷果 180g',
    categoryCode: 'SNK',
    categoryName: '休闲零食',
    barcode: '6935265310018',
    unit: '罐',
    specification: '180g',
    price: 48,
    memberPrice: 42,
    costPrice: 22.5,
    inventory: 86,
    safetyStock: 40,
    tags: ['坚果', '零食'],
    supplier: '上海臻味食品贸易有限公司',
    manager: '王敏',
    status: 'available',
    salesType: 'single',
    createdAt: '2025-05-19 10:20:00',
    updatedAt: '2025-09-27 11:08:00',
  },
  {
    id: 'P-1003',
    productCode: 'P-FR-10009',
    productName: '每日鲜切水果盒（500g）',
    categoryCode: 'FRU',
    categoryName: '果蔬生鲜',
    barcode: '6935265311009',
    unit: '盒',
    specification: '500g/盒',
    price: 28,
    memberPrice: 24.8,
    costPrice: 13,
    inventory: 48,
    safetyStock: 30,
    tags: ['鲜食', '轻食'],
    supplier: '杭州鲜享农业科技有限公司',
    manager: '赵倩',
    status: 'available',
    salesType: 'single',
    createdAt: '2025-07-02 07:35:00',
    updatedAt: '2025-09-29 07:58:00',
  },
  {
    id: 'P-1004',
    productCode: 'P-BK-30005',
    productName: '法式黄油可颂（6只装）',
    categoryCode: 'BAK',
    categoryName: '烘焙面点',
    barcode: '6935265313005',
    unit: '盒',
    specification: '6只/盒',
    price: 36,
    memberPrice: 31.8,
    costPrice: 19,
    inventory: 0,
    safetyStock: 25,
    tags: ['烘焙', '限量'],
    supplier: '杭州云雀烘焙工坊',
    manager: '陈亮',
    status: 'disabled',
    salesType: 'single',
    createdAt: '2025-04-18 06:20:00',
    updatedAt: '2025-09-10 16:28:00',
    remark: '原料供应不足，暂停售卖，预计10月恢复',
  },
  {
    id: 'P-1005',
    productCode: 'P-HS-70002',
    productName: '川味藤椒鸡胸轻食套餐',
    categoryCode: 'HEA',
    categoryName: '健康轻食',
    barcode: '6935265317002',
    unit: '份',
    specification: '420g/份',
    price: 32,
    memberPrice: 28.5,
    costPrice: 16.5,
    inventory: 65,
    safetyStock: 25,
    tags: ['低脂', '轻食'],
    supplier: '杭州尚鲜中央厨房有限公司',
    manager: '苏远',
    status: 'available',
    salesType: 'single',
    createdAt: '2025-06-21 09:05:00',
    updatedAt: '2025-09-30 18:45:00',
  },
  {
    id: 'P-1006',
    productCode: 'P-HS-70008',
    productName: '轻燃控卡三日套餐',
    categoryCode: 'HEA',
    categoryName: '健康轻食',
    barcode: '6935265317008',
    unit: '套',
    specification: '3日套餐',
    price: 168,
    memberPrice: 148,
    costPrice: 86,
    inventory: 28,
    safetyStock: 10,
    tags: ['套餐', '健身'],
    supplier: '杭州尚鲜中央厨房有限公司',
    manager: '苏远',
    status: 'available',
    salesType: 'combo',
    createdAt: '2025-05-08 09:15:00',
    updatedAt: '2025-09-24 17:52:00',
  },
  {
    id: 'P-1007',
    productCode: 'P-SV-90001',
    productName: '企业团餐配送服务',
    categoryCode: 'HOT',
    categoryName: '即热餐饮',
    barcode: '',
    unit: '项',
    specification: '按单结算',
    price: 0,
    memberPrice: 0,
    costPrice: 0,
    inventory: 9999,
    safetyStock: 0,
    tags: ['服务', '企业'],
    supplier: '杭州垂直生活科技有限公司',
    manager: '周杰',
    status: 'available',
    salesType: 'service',
    createdAt: '2025-03-10 11:00:00',
    updatedAt: '2025-09-18 10:18:00',
    remark: '按合同报价执行，金额以实际订单为准',
  },
  {
    id: 'P-1008',
    productCode: 'P-SN-20036',
    productName: '日式蜜汁牛肉干 120g',
    categoryCode: 'SNK',
    categoryName: '休闲零食',
    barcode: '6935265312036',
    unit: '袋',
    specification: '120g',
    price: 32,
    memberPrice: 28.9,
    costPrice: 16,
    inventory: 142,
    safetyStock: 50,
    tags: ['肉干', '高复购'],
    supplier: '杭州臻味食品贸易有限公司',
    manager: '王敏',
    status: 'available',
    salesType: 'single',
    createdAt: '2025-02-26 10:05:00',
    updatedAt: '2025-09-28 13:45:00',
  },
  {
    id: 'P-1009',
    productCode: 'P-DA-60001',
    productName: '一次性环保纸碗 500只装',
    categoryCode: 'DAI',
    categoryName: '日用百货',
    barcode: '6935265316001',
    unit: '箱',
    specification: '500只/箱',
    price: 155,
    memberPrice: 138,
    costPrice: 92,
    inventory: 74,
    safetyStock: 20,
    tags: ['耗材', '大包装'],
    supplier: '苏州启木新材料股份有限公司',
    manager: '刘洁',
    status: 'available',
    salesType: 'single',
    createdAt: '2025-01-18 14:26:00',
    updatedAt: '2025-09-23 15:02:00',
  },
  {
    id: 'P-1010',
    productCode: 'P-GF-80002',
    productName: '门店百元充值卡',
    categoryCode: 'GIF',
    categoryName: '礼品卡券',
    barcode: '',
    unit: '张',
    specification: '面额100元',
    price: 100,
    memberPrice: 100,
    costPrice: 100,
    inventory: 520,
    safetyStock: 100,
    tags: ['卡券', '福利'],
    supplier: '杭州垂直生活科技有限公司',
    manager: '蒋楠',
    status: 'available',
    salesType: 'single',
    createdAt: '2025-07-12 09:50:00',
    updatedAt: '2025-09-20 16:22:00',
  },
];
